services:
  psql_bp:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${QUEST_DB_DATABASE}
      POSTGRES_USER: ${QUEST_DB_USERNAME}
      POSTGRES_PASSWORD: ${QUEST_DB_PASSWORD}
    ports:
      - "${BLUEPRINT_DB_PORT}:5443"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

volumes:
  psql_volume_bp: