### GET request to example server
POST http://localhost:8080/profiles/attendance/00000000-0000-0000-0000-000000000000

###

### Give award
POST http://localhost:8080/profiles/award
Content-Type: application/json

{
  "type": "gold",
  "receiver": "550e8400-e29b-41d4-a716-446655440000",
  "message": "Bedankt voor je hulp bij het project!"
}

###